version: "3.8"
services:
  browservice:
    build: .
    privileged: yes   # For "Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted"
    ports:
      - 127.0.0.1:8098:8080
    volumes:
      - ./.browservice/:/home/browser/.browservice/
