services:
  browservice:
    build: .
    privileged: true  # Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
    restart: unless-stopped
    ports:
      - 127.0.0.1:8098:8080
    volumes:
      - ./.browservice/:/home/browser/.browservice/
